
```{r set_collectors}

ipo_comps = stocks_ipo %>%
    select(id = tase_id) %>%
    distinct()

index_match_table = stocks_ipo %>% 
  select(id_ipo = tase_id) %>% 
  distinct() %>% 
  mutate(id_control = "ta_125")

size_match_table = match_by_target_value(
  ipo_comps = ipo_comps,
  target_df = clean_market_df %>%
    select(-price) %>%
    filter(complete.cases(.)),
  age_threshold = 1 * 252,
  single_match = FALSE
)


book_to_market_match_table = match_by_target_value(
  ipo_comps = ipo_comps,
  target_df = finrep_df,
  age_threshold = 1,
  single_match = FALSE
)


results = list(index = index_match_table,
                        size =  size_match_table,
                        book_to_market = book_to_market_match_table) %>% 
  bind_rows(.id = "benchmark") %>% 
  nest(.by = benchmark,.key = "matching_table")

rm(list = c(str_subset(ls(), "match"), "ipo_comps"))

```

```{r add_price_df}

my_price_df = clean_market_df %>%
  select(-target_value) %>%
  filter(complete.cases(.))

results = results %>%
  mutate(price_df = map(matching_table,
                        ~ merge_ipo_control_prices(price_df = my_price_df,
                                                   matched_sample = .)))

rm(my_price_df, clean_market_df, finrep_df)

```

```{r calculate_bhar}

results = results %>% 
  mutate(bhar = map(price_df, function(temp_price_df){
    
    bhar_horizons = map_dfr(c(1,3,5), function(temp_horizon){
      
      temp_bhar = temp_price_df %>% 
        calculate_bhar_from_price_df(target_duration = 252 * temp_horizon,
                                     duration_tolerance = 0.02) %>% 
        mutate(horizon = temp_horizon)
      
      return(temp_bhar)
  
  
  
  
})
    
    return(bhar_horizons)
    
    
    
    
  }))

```

```{r calculate_car, eval=FALSE}

```


```{r add_monthly_prices, eval=FALSE}

results = results %>% 
  select(benchmark, price_df) %>% 
  mutate(price_df_monthly = map(price_df, convert_to_trading_months))

```

```{r calculate_abnormal_return, eval=FALSE}

results = results %>% 
  mutate(abnormal_return = map(price_df_monthly, average_abnormal_return))

```

```{r calculate_monthly_bhar, eval=FALSE}

results = results %>% 
  mutate(bhar_monthly = map(price_df_monthly, function(temp_price_df){
    
    bhar_horizons = map_dfr(c(1,3,5), function(temp_horizon){
      
      temp_bhar = temp_price_df %>% 
        calculate_bhar_from_price_df(target_duration = 12 * temp_horizon,
                                     duration_tolerance = 0.02) %>% 
        mutate(horizon = temp_horizon)
      
      return(temp_bhar)
  
  
  
  
})
    
    return(bhar_horizons)
    
    
    
    
  }))

```


```{r calculate_ctar, eval=FALSE}

time_index = results %>% 
  slice(1) %>% 
  unnest("price_df") %>% 
  select(date) %>% 
  mutate(date = as.yearmon(date)) %>% 
  distinct()

ipo_dates = stocks_ipo

temp_price = results %>% 
  slice(1) %>% 
  unnest("price_df") %>% 
  mutate(date = as.yearmon(date)) %>% 
  group_by(date, id, id_control) %>% 
  summarise(across(contains("price"), mean), .groups = "drop")

temp_ret = temp_price %>% 
  group_by(id, id_control) %>% 
  arrange(date) %>% 
  mutate(across(contains("price"), ~ . / dplyr::lag(.) - 1)) %>% 
  ungroup() %>% 
  mutate(ctar = price_ipo - price_control) %>% 
  select(date, id, ctar) %>% 
  filter(complete.cases(.))


temp = make_time_series_ipo_list(time_index_df = time_index,
                                 ipo_dates_df = ipo_dates_df,
                                 ipo_duration_threshold = 36)

temp %>% 
  left_join(temp_ret, by = c("date", "id")) %>% 
  filter(complete.cases(.)) %>% 
  group_by(date) %>% 
  summarise(ctar = mean(ctar), .groups = "drop") %>% 
  ggplot(aes(x = ctar)) + 
  geom_density()

```



\subsection{Buy-and-Hold returns}


```{r save_bhar_results}

bhar_returns = results %>%
  select(benchmark, bhar) %>%
  unnest(bhar) %>%
  group_by(benchmark, horizon, id) %>%
  summarise(bhar_abnormal = mean(bhar_abnormal), .groups = "drop_last") %>% 
  mutate(n_comps = length(unique(id))) %>%
  ungroup()

bhar_returns %>% 
  group_by(benchmark, horizon) %>% 
  summarise(across(
    bhar_abnormal,
    .fns = list(
      mean = mean,
      t_stat = ~t_statistic(., n_comps[1]),
      t_sa = ~t_skew_adjusted(., n_comps[1])
    )
  ),
  .groups = "drop") %>%
  #   write_csv(paste0("C:\\Users\\internet",
#                    "\\OneDrive - Bank Of Israel\\research",
#                    "\\tase\\article_digest\\bhar_table.csv"))

```



\subsection{Buy-and-Hold returns using a market index}

```{r sanity_check_index,eval=FALSE}

results %>% 
  filter(benchmark == "index") %>% 
  select(price_df) %>% 
  unnest(cols = c(price_df)) %>%  
  filter(id == 1420) %>% 
  select(date, contains("price")) %>% 
  pivot_longer(-date) %>% 
  group_by(name) %>% 
  mutate(value = value / value[date == min(date)]) %>% 
  ungroup() %>% 
  ggplot(aes(date, value, color = name)) + 
  geom_line() + 
  xlab(NULL) + ylab(NULL) + ggtitle("Azrieli group vs TA 125")
  theme(legend.title = element_blank())

```

```{r sanity_check_bhar_calculation, eval=FALSE}

manual_bhar_index = results %>% 
  filter(benchmark == "index") %>% 
  select(price_df) %>% 
  unnest(cols = c(price_df)) %>% 
  filter(id == 1240) %>% 
  mutate(date = date - min(date)) %>% 
  filter(date == 0 | date <= 252) %>% 
  slice(1, nrow(.)) %>% 
  summarise(across(contains("price"), ~.[2]/.[1]-1)) %>% 
  rename_with(~str_replace(.,"price","bhar"))

all.equal(
  manual_bhar_index,
  results %>%
    filter(benchmark == "index") %>%
    select(bhar) %>%
    unnest(cols = c(bhar)) %>%
    filter(id == 1240) %>%
    filter(horizon == 1) %>%
    select(bhar_ipo, bhar_control)
)

rm(manual_bhar_index)

```

```{r plot_bhar_index_dist}

results %>%
  filter(benchmark == "index") %>%
  select(bhar) %>% 
  unnest(cols = c(bhar)) %>%
  ggplot(aes(x = bhar_abnormal)) + 
  geom_density() + 
  facet_wrap(~horizon) + 
  xlab(NULL) + ylab(NULL) + ggtitle("Buy and Hold index abnormal returns")

```

\subsubsection{Buy-and-Hold returns using control matched by market cap}


```{r sanity_check_bhar_calculation, eval=FALSE}

manual_bhar_size = results %>% 
  filter(benchmark == "size") %>% 
  select(price_df) %>% 
  unnest(cols = c(price_df)) %>% 
  filter(id == 1819) %>% 
  filter(id_control == 345) %>% 
  mutate(date = date - min(date)) %>% 
  filter(date == 0 | date <= 3 * 252) %>% 
  slice(1, nrow(.)) %>% 
  summarise(across(contains("price"), ~.[2]/.[1]-1)) %>% 
  rename_with(~str_replace(.,"price","bhar"))

 
all.equal(
  manual_bhar_size,
  results %>%
    filter(benchmark == "size") %>%
    select(bhar) %>%
    unnest(cols = c(bhar)) %>%
    filter(id == 1819) %>%
    filter(id_control == 345) %>%
    filter(horizon == 3) %>%
    select(bhar_ipo, bhar_control)
)

rm(manual_bhar_size)

```


```{r plot_bhar_size_dist}

results %>%
  filter(benchmark == "size") %>%
  select(bhar) %>%
  unnest(cols = c(bhar)) %>% 
  group_by(id, horizon) %>% 
  summarise(bhar_abnormal = mean(bhar_abnormal), .groups = "drop") %>% 
  ggplot(aes(x = bhar_abnormal)) + 
  geom_density() + 
  facet_wrap(~horizon) + 
  xlab(NULL) + ylab(NULL) + 
  ggtitle("Buy and Hold size abnormal returns")


```


\subsubsection{Match by book to market}

```{r sanity_check_bhar_book_to_market, eval=FALSE}

manual_bhar_book_to_market = results %>% 
  filter(benchmark == "book_to_market") %>% 
  select(price_df) %>% 
  unnest(cols = c(price_df)) %>% 
  filter(id == 1103) %>% 
  filter(id_control == 669) %>% 
  mutate(date = date - min(date)) %>% 
  filter(date == 0 | date <= 1 * 252) %>% 
  slice(1, nrow(.)) %>% 
  summarise(across(contains("price"), ~.[2]/.[1]-1)) %>% 
  rename_with(~str_replace(.,"price","bhar"))


all.equal(
  manual_bhar_book_to_market,
  results %>%
    filter(benchmark == "book_to_market") %>%
    select(bhar) %>%
    unnest(cols = c(bhar)) %>%
    filter(id == 1103) %>%
    filter(id_control == 669) %>%
    filter(horizon == 1) %>%
    select(bhar_ipo, bhar_control)
)

rm(manual_bhar_book_to_market)

```


```{r plot_bhar_book_to_market_dist}

results %>%
  filter(benchmark == "book_to_market") %>%
  select(bhar) %>%
  unnest(cols = c(bhar)) %>% 
  group_by(id, horizon) %>% 
  summarise(bhar_abnormal = mean(bhar_abnormal), .groups = "drop") %>% 
  ggplot(aes(x = bhar_abnormal)) + 
  geom_density() + 
  facet_wrap(~horizon) + 
  xlab(NULL) + ylab(NULL) + 
  ggtitle("Buy and Hold book to market abnormal returns")


```

\subsection{Cumulative abnormal returns}


```{r plot_car}

results %>% 
  select(benchmark, abnormal_return) %>% 
  unnest(cols = c(abnormal_return)) %>% 
  filter(date <= 60) %>% 
  group_by(benchmark) %>% 
  arrange(date) %>% 
  mutate(car = cumsum(average_abnormal_return)) %>% 
  ungroup() %>% 
  ggplot(aes(date, car, color = benchmark)) + 
  geom_line()


```


```{r save_car_results}

results %>%
select(benchmark, abnormal_return) %>%
unnest(cols = c(abnormal_return)) %>%
filter(date <= 60) %>%
group_by(benchmark) %>%
arrange(date) %>%
mutate(car = cumsum(average_abnormal_return)) %>%
ungroup() %>%
filter(date %in% (c(1,3,5) * 12)) %>%
select(-average_abnormal_return) %>%
pivot_wider(names_from = benchmark, values_from = car) %>% 
  write_csv(paste0("C:\\Users\\internet",
                   "\\OneDrive - Bank Of Israel\\research",
                   "\\tase\\article_digest\\car_table.csv"))

```


\subsection{Results}

```{r plot_bhar_by_year}

results %>% 
  filter(benchmark == "index") %>% 
  select(bhar) %>% 
  unnest(cols = "bhar") %>% 
  select(id, bhar_ipo, horizon) %>% 
  left_join(stocks_ipo %>% 
              select(id = tase_id, year) %>% 
              distinct(),by = join_by(id)) %>% 
  group_by(year, horizon) %>% 
  summarise(across(bhar_ipo, list(mean_ret = mean, sd_ret = sd)),
            .groups = "drop") %>% 
  rename_with(~str_remove_all(.,"bhar_ipo_")) %>% 
  ggplot() + 
    geom_point(aes(year, mean_ret)) + 
    geom_errorbar(aes(x = year, ymin = mean_ret - sd_ret,
                      ymax = mean_ret + sd_ret)) + 
  xlab(NULL) + ylab(NULL) + 
  facet_wrap(~horizon, scales = "free")

```


```{r table_bhar}

results %>% 
  select(c("benchmark", "bhar")) %>% 
  unnest(cols = c("benchmark", "bhar")) %>% 
  group_by(benchmark, horizon) %>% 
  summarise(across("bhar_abnormal", list(mean = mean,
                                         median = median)),
            .groups = "drop")


results %>% 
  select(c("benchmark", "bhar")) %>% 
  unnest(cols = c("benchmark", "bhar")) %>% 
  group_by(benchmark, horizon, id) %>% 
  summarise(bhar_abnormal = mean(bhar_abnormal),
            .groups = "drop_last") %>% 
  summarise(across("bhar_abnormal",
                   list(mean = mean,
                        t_stat = ~t.test(.)[["statistic"]])),
            .groups = "drop") %>% 
  rename_with(~str_remove_all(.,pattern = "bhar_abnormal_"))

```

