---
output:
  pdf_document: default
---
\section{Returns calculation}

The return measures used in the paper are:

\begin{itemize}
  \item
  Cumulative average adjusted returns (CAR)
  \item
  Buy and hold abnormal returns (BHAR)
  \item
  Calendar time abnormal returns (CTAR)
\end{itemize}


\subsection{CAR}

Benchmark adjusted returns are calculated as a difference between raw return
and the return of benchmark index.
Thus, the abnormal return is defined as:

\begin{equation*}
  ar_{i,t} = r_{i,t} - r_{benchmark,t}
\end{equation*}

the benchmark return is the average return of the securities constituting
the benchmark:

\begin{equation*}
  r_{benchmark,t} = \sum_{j=1}^{J}{r_{j,t}}
\end{equation*}

where:

$J$ - Set of benchmark companies

And the cumulative abnormal return is given by:

\begin{equation*}
  CAR_{i,\tau} = \sum_{t=1}^{\tau}{ar_{i,t}}
\end{equation*}

where:

$\tau - horizon$


\subsection{BHAR}

The buy-and-hold abnormal return (BHAR) is defined as follows:

\begin{equation*}
  BHAR_{i,T} = \left[\prod_{t = 1}^{T}(1 + r_{i,t}) - 1\right] - 
  \frac{1}{J}\sum_{j=1}^{J}{\left[\prod_{t = 1}^{T}(1 + r_{j,t}) - 1\right]}
\end{equation*}

Where:
$r_{i,t}$ - the return of firm $i$ in month $t$

$r_{m,t}$ - the return of corresponding benchmark in month $t$

\subsubsection{Statistical significance}

I employ a bootstrapped skewness-adjusted t-statistic to correct the
negatively biased t-statistics. I draw 5,000 resamples of size
n (in this case, n = 100), with replacement, from each return series
and calculate a skewness-adjusted t-statistic for each sample, given by

$$t = \sqrt n (S + \frac{1}{3}\hat{\gamma}S^{2} + \frac{1}{6n}\hat{\gamma})$$

where:

\begin{equation*}
  S = \frac{\bar{AR}}{\sigma(AR)}
\end{equation*}

\begin{equation*}
  \hat{\gamma} = \frac{\sum_{i = 1}^{n} (AR_{it} - \bar{AR_{t}^{3}})}{n\sigma(AR)^{3}}
\end{equation*}

\subsubsection{Statistical significance}



Conventional t-statistic

\begin{equation*}
  t = \frac{\overline{AR}_{\tau}}{\sigma(AR_{\tau}) / \sqrt n}
\end{equation*}


Bootstrapped (skewness adjusted) t-statistic

\begin{equation*}
  t_{sa} = \sqrt n \left(S + \frac{1}{3} \hat{\gamma} S^{2} + \frac{1}{6n}
  \hat{\gamma} \right)
\end{equation*}

where:

$AR_{\tau} = BHAR_{i,\tau}$

$S = \frac{\overline{AR}_{\tau}}{\sigma(AR_{\tau})}$

$\hat{\gamma} = \frac{\sum_{i=1}^{n}(AR_{i \tau} - \overline{AR}_{\tau}) ^ 3}{n\sigma(AR_{\tau}) ^ 3}$


\subsection{CTAR}

In order to measure the performance in calendar time I form a portfolio of IPO returns of companies that were born within the previous 36 months. I calculate the returns of this portfolio for each month in the sample and for
each month t I get the return of this month portfolio. The abnormal
calendar time return (CTAR) is calculated as 

\begin{equation*}
  CTAR_{t} = \sum_{i = 1}^{p}(r_{i,t} - r_{benchmark,t})
\end{equation*}

where: 

$r_{p,t}$ - the of portfolio of firms that issued stock in 36 months previous
to month $t$

$r_{benchmark,t}$ - the return of corresponding benchmark in month $t$


\subsection{Control firms matching procedure}
In order to match a control firm for each of the `#r num_ipo` IPOs in `#r data_period` for each IPO comp I take the market value of the IPO on the end 
of the first trading day and match it with the closest market cap company in the
same sector on that day. I allow for maximum difference of 20% in the market cap.

