<!-- import_data -->


```{r load_libraries}

library(tidyverse)

library(xts)

library(lubridate)

library(stargazer)

devtools::load_all()

library(MiscImport)

```


```{r import_cpi}

cpi_df = read_csv(paste0(Sys.getenv("USERPROFILE"),
                         "\\OneDrive - Bank Of Israel\\Data",
                         "\\BoI\\monetary_data\\cpi.csv"),
                  show_col_types = FALSE,
                  skip = 15,col_names = c("date","cpi")) %>%
  mutate(date = dmy(date)) %>%
  group_by(date = as.yearqtr(date)) %>%
  summarise(cpi = mean(cpi), .groups = "drop") %>%
  filter(date >= as.yearqtr("2000 Q1")) %>%
  mutate(cpi = cpi / cpi[date == as.yearqtr("2000 Q1")])


```


```{r import_mcap_from_vladimir}

vladimir_mcap = read_csv(paste0(Sys.getenv("USERPROFILE"),
                                "\\OneDrive - Bank Of Israel",
                                "\\Data\\BoI\\Finrep",
                                "\\market_cap_from_vladimir.csv"),
                         show_col_types = FALSE) %>% 
  select(date_yearqtr = date, sec_id = msp_brs,
         tase_id = MSP_HVR, market_value = AvgMV) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(date_yearqtr = dmy(date_yearqtr)) %>% 
  mutate(date_yearqtr = as.yearqtr(date_yearqtr))

```

```{r import_finrep_df}


complete_finrep_with_vladimir_data = function(finrep_df, vladimir_mcap){
  
  finrep_df = finrep_df  %>% 
  left_join(vladimir_mcap %>% 
              group_by(tase_id,date_yearqtr) %>% 
              summarise(mcap_vladimir = mean(market_value, na.rm = TRUE),
                        .groups = "drop"),
            by = c("tase_id","date_yearqtr")) %>% 
  mutate(market_value = coalesce(market_value, mcap_vladimir)) %>% 
  select(-mcap_vladimir) %>% 
  filter(!is.na(market_value))
  
  return(finrep_df)
 
}



finrep_df_raw = import_boi_oracle_finrep_data(paste0(Sys.getenv("USERPROFILE"),
                                     "\\OneDrive - Bank Of Israel\\Data",
                                     "\\BoI\\Finrep",
                                     "\\finrep_full_data_2023-05-11.rds"),
                              data_frequency = "quarterly")


finrep_df = finrep_df_raw %>% 
  select(tase_id, date_yearqtr, market_value,
         total_assets,total_liabilities) %>% 
  mutate(book_value = total_assets - total_liabilities) %>% 
  select(-contains("total")) %>% 
  filter(!is.na(book_value)) %>% 
  filter(book_value >= 0)%>% 
  mutate(across(c("market_value"),~ .* 10 ^ -3))

finrep_df = finrep_df %>% 
  complete_finrep_with_vladimir_data(vladimir_mcap)

finrep_df = finrep_df %>% 
  mutate(book_to_market = book_value / market_value) %>% 
  select(tase_id, date_yearqtr,market_value, book_to_market)



rm(finrep_df_raw,vladimir_mcap, complete_finrep_with_vladimir_data)

```

```{r import_ipo_list}

delisting_dates = read_csv(paste0(Sys.getenv("USERPROFILE"),
                                  "\\OneDrive - Bank Of Israel\\Data",
                                  "\\TASE\\TASE Comps list_revised.csv"),
                           show_col_types = FALSE) %>% 
  rename_with(tolower) %>% 
  filter(delisted == 1) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  select(tase_id, delisting_date, delisting_reason)

stocks_ipo = read_csv(paste0(Sys.getenv("USERPROFILE"),
                             "\\OneDrive - Bank Of Israel",
                             "\\Data\\TASE liquidity",
                             "\\michael files\\stocks_ipo.csv"),
                      show_col_types = FALSE) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  select(-comp_name_heb, -prospectus_date)

stocks_ipo = stocks_ipo %>% 
  left_join(delisting_dates, by = "tase_id")

stocks_ipo = stocks_ipo %>% 
  mutate(tase_id = recode(tase_id,
                          `456` = "259")) %>% 
  unite(c("year", "month"),col = "date", sep = "-",remove = FALSE) %>% 
  mutate(date = as.yearqtr(date, format = c("%Y-%m"))) %>% 
  select(-month)

stocks_ipo = stocks_ipo %>% 
  left_join(finrep_df,
            by = c("tase_id","date" = "date_yearqtr")) %>% 
  mutate(market_value = market_value * 10 ^ -3)

stocks_ipo = stocks_ipo %>% 
  left_join(cpi_df, by = "date") %>% 
  mutate(across(c("domestic_issue", "market_value"), ~ . / cpi,
         .names = "{.col}_real")) %>% 
  select(-cpi)

rm(delisting_dates)

```

```{r import_ta_125}

ta_125 = read_csv(paste0(Sys.getenv("USERPROFILE"),
                         "\\OneDrive - Bank Of Israel\\Data",
                         "\\TASE liquidity\\michael files",
                         "\\TA125.csv"),
                  show_col_types = FALSE) %>% 
  mutate(date = dmy(date))

```

```{r import_tase_sector, eval=FALSE}

tase_sector_df = read_csv(paste0(Sys.getenv("USERPROFILE"),
                                 "\\OneDrive - Bank Of Israel\\Data",
                                 "\\TASE liquidity\\michael files",
                                 "\\tase_sector_and_sub_sector_classification.csv"),
                          show_col_types = FALSE) %>% 
  select(-comp_name_heb) %>% 
  filter(!tase_sector == "#N/A") %>% 
  mutate(date = as.yearmon(date, format = "%m/%d/%Y")) %>% 
  mutate(across(-date, as.character)) %>% 
  select(-tase_sub_sector)

```

```{r import_market_df, cache=TRUE}

# market_df_filepath = paste0(Sys.getenv("USERPROFILE"),
#                                 "\\OneDrive - Bank Of Israel\\Data",
#                                 "\\TASE liquidity\\Rdata files",
#                                 "\\market_data_2023-02-15.rds")
# 
# market_df = import_boi_market_data(market_df_filepath) %>%
#   calculate_adjusted_price()
# 
# rm(market_df_filepath)
# 
# 
# delisted_files = list.files(paste0(Sys.getenv("USERPROFILE"),
#                                    "\\OneDrive - Bank Of Israel\\Data",
#                                    "\\TASE liquidity\\michael files",
#                                    "\\files_from_TASE_website",
#                                    "\\delisted_firms_prices"),
#                             full.names = TRUE)
# 
# delisted_market_df = map_dfr(delisted_files,
#                              function(temp_file_name){
# 
#   temp_id = str_extract(temp_file_name, "[0-9]{4}_[0-9]+")
# 
#   temp_tase_id = str_extract(temp_id, "^[0-9]{4}")
# 
#   temp_sec_id = str_extract(temp_id, "_[0-9]+$") %>%
#     str_remove("_")
# 
#   temp_price_df = read_csv(temp_file_name, skip = 1, show_col_types = FALSE) %>%
#   select(c(1,3,6,9)) %>%
#   set_names(c("date","close_rate","base_rate","market_value")) %>%
#   mutate(tase_id = temp_tase_id) %>%
#   mutate(sec_id = temp_sec_id) %>%
#   mutate(date = dmy(date)) %>%
#   arrange(date) %>%
#   calculate_adjusted_price()
# 
#   return(temp_price_df)
# 
# }) %>% 
#   mutate(market_value = market_value * 10 ^ 3)
# 
# missing_market_df = map_dfr(c("1514_1109644","1108_1108638"),
#                             function(temp_id){
# 
# 
#   temp_file_name = paste0("C:\\Users\\internet",
#                      "\\OneDrive - Bank Of Israel\\Data",
#                      "\\TASE liquidity\\michael files\\files_from_TASE_website",
#                      "\\raw_format\\",temp_id,".csv")
# 
#   temp_tase_id = str_extract(temp_id, "^[0-9]{4}")
# 
#   temp_sec_id = str_extract(temp_id, "_[0-9]+$") %>%
#     str_remove("_")
# 
#   temp_price_df = read_csv(temp_file_name, skip = 2, show_col_types = FALSE) %>%
#   select(c(1,4,7,11)) %>%
#   set_names(c("date","close_rate","base_rate","market_value")) %>%
#   mutate(tase_id = temp_tase_id) %>%
#   mutate(sec_id = temp_sec_id) %>%
#   mutate(date = dmy(date)) %>%
#   arrange(date) %>%
#   calculate_adjusted_price()
# 
#   return(temp_price_df)
# 
# }) %>% 
#   mutate(market_value = market_value * 10 ^ 3)
# 
# names_vec = c("date","tase_id","sec_id","close_adjusted","market_value")
# 
# market_data_for_ipo = delisted_market_df %>%
#   select(names_vec) %>%
#   bind_rows(missing_market_df %>%
#               select(names_vec)) %>%
#   bind_rows(market_df %>%
#               select(names_vec))
# 
# write_rds(market_data_for_ipo,paste0(Sys.getenv("USERPROFILE"),
#                             "\\OneDrive - Bank Of Israel\\Data",
#                             "\\TASE liquidity\\Rdata files",
#                             "\\working_data\\market_data_for_ipo.rds"))


market_df = read_rds(paste0(Sys.getenv("USERPROFILE"),
                            "\\OneDrive - Bank Of Israel\\Data",
                            "\\TASE liquidity\\Rdata files",
                            "\\working_data\\market_data_for_ipo.rds"))

```

