---
title: "temp"
subtitle: 'Preliminary draft'
author: "Michael Gurkov"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
abstract: "Text for abstract"
bibliography: ipo_long_run.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,echo = FALSE,
  message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r get_bib_filepath, include = FALSE}

file.copy(paste0(Sys.getenv("USERPROFILE"),
                 "\\OneDrive - Bank Of Israel",
                 "\\References\\ipo_long_run.bib"),
          "ipo_long_run.bib")

```


A seminal paper that analyses the long run performance of IPO is @RITTER1991
The author studies a sample of US IPO's that went public during 1975-1984 period.
The findings confirm that in the 3 years after going public the IPO's
are underpriced relative to comparable traded firms (matched by size and industry)


\section{References}

<div id="refs"></div>
