
```{r load_libraries}

library(tidyverse)

library(xts)

library(lubridate)

devtools::load_all()

# library(MiscImport)

```


```{r import_ipo_list}

stocks_ipo = read_csv(paste0(Sys.getenv("USERPROFILE"),
                             "\\OneDrive - Bank Of Israel",
                             "\\Data\\TASE liquidity",
                             "\\michael files\\stocks_ipo.csv"),
                      show_col_types = FALSE) %>% 
  mutate(tase_id = as.character(tase_id))


```

```{r import_ta_125}

ta_125 = read_csv(paste0(Sys.getenv("USERPROFILE"),
                         "\\OneDrive - Bank Of Israel\\Data",
                         "\\TASE liquidity\\michael files",
                         "\\TA125.csv"), show_col_types = FALSE)

```

```{r import_market_df}


market_file_path = paste0(Sys.getenv("USERPROFILE"),
                          "\\OneDrive - Bank Of Israel\\Data",
                          "\\TASE liquidity\\Rdata files",
                          "\\market_data_2022-11-15.rds")


market_df  = import_boi_market_data(market_file_path) %>% 
  filter(!is.na(close))

rm(market_file_path)






```


```{r plot_ipo_price_itai, eval=FALSE}

itai_ipos = read_csv(paste0("C:\\Users\\internet",
                             "\\OneDrive - Bank Of Israel",
                             "\\Data\\TASE liquidity",
                             "\\michael files\\itai_ipos.csv"),
                      show_col_types = FALSE) %>% 
  mutate(tase_id = as.character(tase_id))


market_df %>% 
  inner_join(select(itai_ipos, tase_id)) %>% 
  filter(date >= dmy("30-06-2021") & date <= dmy("31-01-2022")) %>% 
  group_by(date) %>% 
  summarise(market_value = sum(market_value, na.rm = TRUE),
            .groups = "drop") %>% 
  mutate(market_value = market_value /
           market_value[date == min(date)] * 100) %>% 
  left_join(ta_125 %>% 
              select(1:2) %>% 
              set_names(c("date"),"ta_125") %>% 
              mutate(date = dmy(date)) %>% 
              filter(date >= dmy("30-06-2021") & 
                       date <= dmy("31-01-2022")) %>% 
              mutate(ta_125 = ta_125 / ta_125[date == min(date)] * 100),
            by = "date") %>% 
  pivot_longer(-date) %>% 
  # filter(date<= dmy("20-01-2022")) %>% 
  ggplot(aes(date, value, color = name)) + 
  geom_line() + 
  ylim(c(90,125))

```

```{r check_for_specific_case, eval=FALSE}

market_df %>% 
  filter(tase_id == 1092) %>% 
  select(tase_id, sec_id, date, close) %>% 
  mutate(trade_duration = date - min(date)) %>% 
  filter(trade_duration == 0 | trade_duration == 1094) %>% 
  arrange(date) %>% 
  summarise(sec_ret = (close[2] / close[1] - 1) / 3)


ret_df %>% 
  filter(tase_id == 1092)


```

# Desc stats



# Long run performance

In order to asses the long run performance of IPO's I calculate the buy and hold return 


```{r cumulative_returns}

cum_ret_df = price_df %>% 
  group_by(tase_id, sec_id, date = as.yearmon(date)) %>% 
  summarise(close = mean(close, na.rm = TRUE), .groups = "drop") %>% 
  group_by(tase_id, sec_id) %>% 
  arrange(date) %>% 
  mutate(trade_periods = date - date[1]) %>% 
  mutate(ret = log(close) - log(close[1])) %>% 
  ungroup()


```


```{r plot_cum_ret}

cum_ret_df  %>% 
  filter(trade_periods <= 12 * 5) %>%
  group_by(trade_periods) %>% 
  summarise(across(ret,.fns = list(mean = mean,
                                   median = median),
                   .names = "{.col}_{.fn}")) %>% 
  pivot_longer(-trade_periods, names_to = "metric") %>% 
  mutate(metric = str_remove(metric,"ret_")) %>% 
  # group_by(metric) %>% 
  # arrange(trade_periods) %>% 
  # mutate(value = slide_dbl(value, mean,.before = 5,.after = 5)) %>% 
  # ungroup() %>% 
  ggplot(aes(as.numeric(trade_periods), value, color = metric)) + 
  geom_line()
  

```


```{r calculate_ret}

price_df = market_df %>% 
  select(tase_id, sec_id,date, close) %>% 
  inner_join(stocks_ipo %>% 
               select(tase_id))

index_df = ta_125 %>% 
  rename(index = ta_125)

ret_df = calculate_cumulative_return(price_df = price_df,
                                     index_df = index_df,
                                     horizon = 365 * 3) %>% 
  mutate(across(contains("ret"), ~ . / 3)) %>% 
  mutate(horizon = 3) %>% 
  bind_rows(calculate_cumulative_return(price_df = price_df,
                                     index_df = index_df,
                                     horizon = 365 * 5) %>% 
  mutate(across(contains("ret"), ~ . / 5)) %>% 
  mutate(horizon = 5)) %>% 
  bind_rows(calculate_cumulative_return(price_df = price_df,
                                     index_df = index_df,
                                     horizon = 365 * 1) %>% 
  mutate(across(contains("ret"), ~ . / 1)) %>% 
  mutate(horizon = 1))


ret_df = ret_df %>% 
  left_join(stocks_ipo %>% 
              select(tase_id, tase_sector, year) %>% 
              distinct(), by = "tase_id")

```


```{r plot_ipo_long_run_performance_by_sector}

library(tidytext)


ret_df %>% 
  select(-year) %>%
  pivot_longer(-c(tase_id,sec_id,tase_sector, horizon),
               names_to = "adjustment") %>% 
  group_by(horizon,tase_sector,adjustment) %>% 
  summarise(avg = mean(value, na.rm = TRUE),
            med = median(value, na.rm = TRUE),
            .groups = "drop") %>% 
  filter(adjustment == "sec_ret_adj") %>%
  select(-adjustment) %>% 
  pivot_longer(-c(tase_sector, horizon)) %>% 
  ggplot(aes(x = value,
             y = reorder_within(tase_sector, value, horizon)),
             fill = name) + 
  geom_col(position = "dodge") + 
  facet_wrap(~horizon, scales = "free") + 
  scale_y_reordered() +
  scale_x_continuous(labels = scales::percent_format()) +
  xlab(NULL) + ylab(NULL)
  


# ret_df %>% 
#   select(contains("tase"), contains("ret")) %>%
#   pivot_longer(-c(tase_id,tase_sector),
#                names_to = "adjustment") %>% 
#   group_by(adjustment, tase_sector) %>% 
#   summarise(avg = mean(value),
#             .groups = "drop") %>% 
#   pivot_wider(names_from = adjustment, values_from = avg) %>% 
  # write_csv(paste0("C:\\Users\\internet",
  #                  "\\OneDrive - Bank Of Israel\\current_work",
  #                  "\\annual_report\\2022\\data",
  #                  "\\plots\\long_run_ipo_by_sector.csv"))

```



```{r plot_ipo_long_run_performance_by_year}

ret_df %>% 
  select(tase_id, year, contains("ret")) %>%
  pivot_longer(-c(tase_id, year),
               names_to = "adjustment") %>% 
  group_by(adjustment, year) %>% 
  summarise(avg = mean(value), med = median(value),
            .groups = "drop") %>% 
  pivot_longer(-c(adjustment,year)) %>% 
  ggplot(aes(x = year,
             y = value,
             fill = name)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~adjustment, scales = "free") + 
  scale_y_continuous(labels = scales::percent_format()) +
  xlab(NULL) + ylab(NULL)


# ret_df %>% 
#   select(tase_id, year, contains("ret")) %>%
#   pivot_longer(-c(tase_id, year),
#                names_to = "adjustment") %>% 
#   group_by(adjustment, year) %>% 
#   summarise(avg = mean(value),
#             .groups = "drop") %>% 
#   pivot_wider(names_from = "adjustment",values_from = "avg") %>% 
#   write_csv(paste0("C:\\Users\\internet",
#                    "\\OneDrive - Bank Of Israel\\current_work",
#                    "\\annual_report\\2022\\data",
#                    "\\plots\\long_run_ipo_by_year.csv"))

  
  


```

