---
output:
  rmarkdown::beamer_presentation
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,echo = FALSE,
  message = FALSE,warning = FALSE,
  comment = "#>"
)
```


<!-- import_data -->


```{r load_libraries}

library(tidyverse)

library(xts)

library(lubridate)

library(stargazer)

devtools::load_all()

# library(MiscImport)

```


```{r import_ta_125}

ta_125 = read_csv(paste0(Sys.getenv("USERPROFILE"),
                         "\\OneDrive - Bank Of Israel\\Data",
                         "\\TASE liquidity\\michael files",
                         "\\TA125.csv"),
                  show_col_types = FALSE) %>% 
  mutate(date = dmy(date))

```

```{r import_market_df, cache=TRUE}

market_df_filepath = paste0(Sys.getenv("USERPROFILE"),
                                "\\OneDrive - Bank Of Israel\\Data",
                                "\\TASE liquidity\\Rdata files",
                                "\\market_data_2022-12-12.rds")

market_df = import_boi_market_data(market_df_filepath) %>% 
  calculate_adjusted_price() %>% 
  filter(date <= max(ta_125$date))

rm(market_df_filepath)

```

```{r import_ipo_list}

stocks_ipo = read_csv(paste0(Sys.getenv("USERPROFILE"),
                             "\\OneDrive - Bank Of Israel",
                             "\\Data\\TASE liquidity",
                             "\\michael files\\stocks_ipo.csv"),
                      show_col_types = FALSE) %>% 
  mutate(tase_id = as.character(tase_id))

stocks_ipo = stocks_ipo %>% 
  mutate(tase_id = recode(tase_id,
                          `456` = "259"))

ipo_trade_dur_df = market_df %>% 
  group_by(tase_id, sec_id) %>% 
  summarise(tibble(first_trade_year = year(min(date)),
                   trade_years = (max(date) - min(date)) %/% dyears(1)),
            .groups = "drop")

stocks_ipo = stocks_ipo %>% 
  left_join(ipo_trade_dur_df, by = "tase_id") %>% 
  arrange(tase_id) %>% 
  filter(!is.na(trade_years))



num_ipo = stocks_ipo %>% 
  count(tase_id, sort = TRUE)


stocks_ipo = stocks_ipo %>% 
  inner_join(num_ipo %>% 
               filter(n == 1) %>% 
               select(tase_id), by = "tase_id")

rm(ipo_trade_dur_df)

```


<!-- Matching by sector -->


```{r match_control_comps}

tase_sector_df = read_csv(paste0(Sys.getenv("USERPROFILE"),
                                 "\\OneDrive - Bank Of Israel\\Data",
                                 "\\TASE liquidity\\michael files",
                                 "\\tase_sector_classification.csv"),
                          show_col_types = FALSE) %>% 
  select(-comp_name_hebrew) %>% 
  filter(!tase_sector == "#N/A") %>% 
  mutate(date = as.yearmon(date, format = "%d/%m/%Y")) %>% 
  mutate(across(-date, as.character)) %>% 
  select(-tase_sub_sector)


ipo_control_match_df = match_control_group(market_df,
                                           tase_sector_df,stocks_ipo)

rm(tase_sector_df)

```



```{r price_df}

price_df = make_price_df(market_df,ipo_control_match_df,ta_125)


```


```{r cumulative_returns}

ret_df = calculate_return_df(price_df)

cum_ret_df = ret_df %>% 
  calculate_cum_return()

```



```{r best_ipos, eval=FALSE}

best_ipos_id = ret_df %>% 
  filter(month <= 36) %>%
  filter(adjustment_type == "index_ret") %>% 
  group_by(id) %>% 
  summarise(value = sum(value), .groups = "drop") %>% 
  slice_max(value, n = 3)


```



```{r clean_up, eval=FALSE}

rm(ipo_control_match_df,ta_125,ret_df, market_df)

```


# Examples


<!-- 1468_1105204 -->


```{r compare_prices_with_index}


temp_price_1468 = market_df %>% 
  filter(tase_id == 1468) %>% 
  select(date,close_adjusted) %>% 
  left_join(ta_125, by = "date") %>% 
  rename(close = close_adjusted, index = ta_125) %>% 
  mutate(month = as.numeric(date - min(date)) %/% 22 + 1) %>% 
  group_by(month) %>% 
  summarise(across(c("close", "index"), ~mean(., na.rm = TRUE)),
            .groups = "drop")


# all.equal(temp_price_1468, price_df %>%
#   filter(id == "1468_1105204") %>% 
#   select(month, close, index))

# temp_price_1468 %>% 
#   mutate(across(c("close", "index"), ~./.[month == min(month)])) %>% 
#   pivot_longer(-month) %>% 
#   ggplot(aes(month, value, color = name)) + 
#   geom_line() + 
#   xlab(NULL) + ylab(NULL) + ggtitle("Price trajectory of 1468 vs index")


```


```{r calculate_returns}

temp_ret_1468 = temp_price_1468  %>% 
  mutate(across(c("close", "index"), ~ . / lag(.) - 1,
                .names = "{.col}_ret")) %>% 
  filter(complete.cases(.)) %>% 
  select(month, close_ret, index_ret) %>% 
  mutate(index_adjusted_ret = close_ret - index_ret)

# all.equal(temp_ret_1468 %>% 
#             select(month,close_ret,index_adjusted_ret),
#           ret_df %>%
#             filter(id == "1468_1105204") %>% 
#             filter(!adjustment_type == "control_ret") %>% 
#             pivot_wider(names_from = "adjustment_type") %>% 
#             select(month,close_ret,index_adjusted_ret = index_ret))


# temp_ret_1468 %>% 
#   mutate(across(-month, cumsum)) %>% 
#   pivot_longer(-month) %>% 
#   ggplot(aes(month, value, color = name)) + 
#   geom_line()

```


```{r plot}

temp_plot_df = temp_price_1468 %>% 
  mutate(across(-month, ~ . / .[month == 1])) %>%
  mutate(category = "price") %>% 
  pivot_longer(-c(month, category)) %>% 
  bind_rows(temp_ret_1468 %>% 
              rename_with(.cols = ends_with("_ret"),
                          .fn = ~str_remove(.,"_ret")) %>% 
              mutate(category = "ret") %>% 
              pivot_longer(-c(month, category))) %>% 
  bind_rows(temp_ret_1468 %>% 
              rename_with(.cols = ends_with("_ret"),
                          .fn = ~str_remove(.,"_ret")) %>% 
              mutate(across(-month, cumsum)) %>% 
              mutate(category = "cumsum") %>% 
              pivot_longer(-c(month, category)))

temp_plot_df %>% 
  filter(month < 40) %>%
  ggplot(aes(month, value, color = name)) + 
  geom_line() + 
  facet_wrap(~category, scales = "free") + 
  xlab(NULL) + ylab(NULL) + ggtitle("1468 performance") + 
  theme(legend.title = element_blank())

```


```{r}

temp = temp_plot_df %>% 
  # filter(category %in% c("price","ret")) %>% 
  pivot_wider(names_from = c("name","category"))


```



# IPO

```{r plot_IPO}

ipo_stats_by_year = stocks_ipo %>%
  select(-comp_name_heb) %>%
  group_by(year) %>%
  summarise(num_ipo = length(domestic_issue),
            total_domestic_issue = sum(domestic_issue), .groups = "drop")

ipo_stats_by_year %>%
  ggplot(aes(year, num_ipo)) +
  geom_col() +
  xlab(NULL) + ylab(NULL) + ggtitle("Number of IPO comps")

```


# IPO by sectors

```{r plot_IPO_by_sectors}

stocks_ipo %>%
  count(year, tase_sector) %>%
  mutate(tase_sector = factor(tase_sector)) %>%
  mutate(tase_sector = fct_lump_n(tase_sector, n = 5)) %>%
  ggplot(aes(year, n)) +
  geom_col(aes(fill = tase_sector)) +
  scale_fill_viridis_d() +
  xlab(NULL) + ylab(NULL) + ggtitle("IPO by sector")

```


```{r plot_attrition, eval=FALSE}

cum_ret_df  %>%
  inner_join(stocks_ipo %>%
               select(tase_id),by = "tase_id") %>%
  select(month, tase_id, sec_id) %>%
  distinct() %>%
  count(month,name = "num_of_comps") %>%
  ggplot(aes(month,num_of_comps)) +
  geom_line() +
  xlab(NULL) + ylab(NULL) +
  ggtitle("Number of trading IPO companies (years since IPO)")



```

```{r motivating_example, eval=FALSE}


market_df %>%
  select(tase_id, sec_id, date, close_adjusted) %>%
  inner_join(stocks_ipo %>%
               select(tase_id) %>%
               slice_sample(n = 15)) %>%
  left_join(ta_125, by = "date") %>%
  group_by(tase_id, sec_id) %>%
  arrange(date) %>%
  mutate(across(c("close_adjusted", "ta_125"), ~./.[1])) %>%
  ungroup() %>%
  pivot_longer(-c(tase_id, sec_id, date)) %>%
  ggplot(aes(date, value, color = name)) +
  geom_line() +
  facet_wrap(~tase_id, scales = "free")
  ggplot(aes(date))



```

# Cumulative returns

```{r plot_cum_ret}

cum_ret_df %>%
  ggplot(aes(month, value, color = adjustment_type)) +
  geom_line() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap( ~ summary_measure, scales = "free") +
  # scale_x_continuous(breaks = seq(0,10,2)) +
  xlab("Months since IPO") + ylab(NULL) +
  ggtitle("Cumulative returns since IPO") +
  theme(legend.title = element_blank())



```



