
```{r load_libraries}

library(tidyverse)

library(xts)

library(lubridate)

library(stargazer)

devtools::load_all()

# library(MiscImport)

```

```{r import_market_df}

market_df_filepath = paste0(Sys.getenv("USERPROFILE"),
                                "\\OneDrive - Bank Of Israel\\Data",
                                "\\TASE liquidity\\Rdata files",
                                "\\market_data_2023-01-01.rds")

market_df = import_boi_market_data(market_df_filepath) %>% 
  select(-c("turnover","volume","public_holding_percent")) %>% 
  calculate_adjusted_price()

rm(market_df_filepath)

```

```{r import_ipo_list}

stocks_ipo = read_csv(paste0(Sys.getenv("USERPROFILE"),
                             "\\OneDrive - Bank Of Israel",
                             "\\Data\\TASE liquidity",
                             "\\michael files\\stocks_ipo.csv"),
                      show_col_types = FALSE) %>% 
  filter(residensce == "israel") %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(tase_id = recode(tase_id,
                          `456` = "259"))

cpi_df = read_csv(paste0(Sys.getenv("USERPROFILE"),
                         "\\OneDrive - Bank Of Israel\\Data",
                         "\\BoI\\monetary_data\\cpi.csv"),
                  show_col_types = FALSE,
                  skip = 15,col_names = c("date","cpi")) %>% 
  mutate(date = dmy(date)) %>% 
  group_by(year = year(date)) %>% 
  summarise(cpi = mean(cpi), .groups = "drop") %>% 
  filter(year >= 2000) %>% 
  mutate(cpi = cpi / cpi[year == 2000])


stocks_ipo = stocks_ipo %>% 
  left_join(cpi_df, by = "year") %>% 
  mutate(real_domestic_issue = domestic_issue / cpi) %>% 
  select(-cpi)

rm(cpi_df)

# ipo_trade_dur_df = market_df %>% 
#   group_by(tase_id, sec_id) %>% 
#   summarise(tibble(first_trade_year = year(min(date)),
#                    trade_years = (max(date) - min(date)) %/% dyears(1)),
#             .groups = "drop")
# 
# stocks_ipo = stocks_ipo %>% 
#   left_join(ipo_trade_dur_df, by = "tase_id") %>% 
#   arrange(tase_id) %>% 
#   filter(!is.na(trade_years))
# 
# 
# 
# num_ipo = stocks_ipo %>% 
#   count(tase_id, sort = TRUE)
# 
# 
# stocks_ipo = stocks_ipo %>% 
#   inner_join(num_ipo %>% 
#                filter(n == 1) %>% 
#                select(tase_id), by = "tase_id")
# 
# rm(ipo_trade_dur_df)

```

\section{Entire sample}

```{r compare_issue_data_with_entire_sample, eval=FALSE}

market_df %>% 
  unite(id, c("tase_id","sec_id")) %>% 
  group_by(id) %>% 
  summarise(year = year(min(date)), .groups = "drop") %>% 
  count(year,name = "ipos_entire_sample") %>% 
  full_join(stocks_ipo %>% 
              count(year, name = "ipo_by_tase_list"), by = "year") %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1990) %>% 
  ggplot(aes(as.character(year), value, fill = name)) + 
  geom_col(position = "dodge") + 
  xlab(NULL) + ylab(NULL) + ggtitle("Comparison between TASE list and entire sample")


```

```{r compare_2021, eval=FALSE}

entire_sample_comps = market_df %>% 
  unite(id, c("tase_id","sec_id")) %>% 
  group_by(id) %>% 
  summarise(year = year(min(date)), .groups = "drop") %>% 
  separate(id, into = c("tase_id","sec_id"))

tase_list_comps = stocks_ipo %>% 
  select(tase_id, year)

entire_sample_comps %>% 
  anti_join(tase_list_comps, by = c("tase_id","year")) %>% 
  write_csv(paste0(Sys.getenv("USERPROFILE"),
                   "\\OneDrive - Bank Of Israel\\Data",
                   "\\TASE liquidity\\michael files",
                   "\\tase_list_checks\\compare_sample_vs_tase_list.csv"))

```

```{r bhar_returns_for_entire_sample}

matched_entire_sample = match_comps_by_market_value(
  ipo_comps = market_df %>% 
    select(tase_id) %>% 
    distinct(), market_df)

price_df_entire_sample_single = make_price_df(market_df, matched_entire_sample)

bhar_daily_entire_sample_single = map_dfr(c(3,5), function(temp_horizon){
  
  temp_df = price_df_entire_sample_single %>% 
    calculate_bhar_from_price_df(target_duration = 251 * temp_horizon) %>% 
    mutate(horizon = temp_horizon)

})

bhar_daily_entire_sample_single %>% 
  group_by(horizon) %>% 
  summarise(across(c(contains("bhar"), duration), median),
            num_comps = n())



```



\subsection{Buy-and-Hold returns using a single matched firm}

\subsubsection{Match on size}

<!-- daily calculation -->

```{r match_and_calculate_single_daily}

ipo_comps = stocks_ipo %>% 
  select(tase_id) %>% 
  distinct()

matched_sample_single = match_comps_by_market_value(ipo_comps,market_df)

price_df_single = make_price_df(market_df, matched_sample_single)

bhar_daily_single = map_dfr(c(3,5), function(temp_horizon){
  
  temp_df = price_df_single %>% 
    calculate_bhar_from_price_df(target_duration = 251 * temp_horizon) %>% 
    mutate(horizon = temp_horizon)
  
  
  
  
})


```

```{r plot_matching, eval=FALSE}

library(tidygraph)

library(igraph)

matched_graph = matched_sample %>%
  slice(1:5) %>% 
  as_tbl_graph(directed = FALSE)

matched_graph = matched_graph %>% 
  activate(nodes) %>% 
  mutate(lab = name) %>% 
  mutate(type = if_else(lab %in% unique(matched_sample$id_ipo),
                        TRUE, FALSE))

plot(matched_graph, layout = layout_as_bipartite, vertex.size = 100)

```

```{r output_table_bhar_daily_single}

bhar_daily_single %>% 
  group_by(horizon) %>% 
  summarise(across(c(contains("bhar"), duration), median))


```

<!-- monthly_calculation -->


```{r calculate_benchmark_performance_monthly}

price_df_month_single = price_df_single %>% 
  group_by(id, id_control) %>% 
  arrange(date) %>% 
  mutate(date = as.numeric(date - min(date)) %/% 21 + 1) %>% 
  group_by(id, id_control, date) %>% 
  summarise(across(contains("price"), mean), .groups = "drop")

bhar_monthly_single = map_dfr(c(3,5), function(temp_horizon){
  
  temp_df = price_df_month_single %>% 
    calculate_bhar_from_price_df(target_duration = 12 * temp_horizon) %>% 
    mutate(horizon = temp_horizon)
  
  
  
  
})

```


```{r output_table_bhar_monthly}

bhar_monthly_single %>% 
  group_by(horizon) %>% 
  summarise(across(c(contains("bhar"), duration), mean))

```

\subsubsection{Match on book to market}



\subsection{Buy-and-Hold returns using a portfolio of matched firms}


<!-- daily calculation -->


```{r match_multiple_control_firm_by_size_multiple}

matched_sample_multiple = match_comps_by_market_value(ipo_comps,market_df,
                                                      single_match = FALSE)

price_df_multiple = make_price_df(market_df, matched_sample_multiple)

bhar_daily_multiple = map_dfr(c(3,5), function(temp_horizon){
  
  temp_df = price_df_multiple %>% 
    calculate_bhar_from_price_df(target_duration = 251 * temp_horizon) %>% 
    mutate(horizon = temp_horizon)
  
  
  
  
})



```

```{r output_table_bhar_daily_multiple}

bhar_daily_multiple %>% 
  group_by(horizon) %>% 
  summarise(across(c(contains("bhar"), duration), median))


```



<!-- monthly_calculation -->


```{r calculate_benchmark_performance_monthly_multiple}


price_df_month_multi = price_df_multi %>% 
  group_by(id, id_control) %>% 
  arrange(date) %>% 
  mutate(date = as.numeric(date - min(date)) %/% 21 + 1) %>% 
  group_by(id, id_control, date) %>% 
  summarise(across(contains("price"), mean), .groups = "drop")

bhar_monthly_multi = map_dfr(c(3,5), function(temp_horizon){
  
  temp_df = price_df_month_multi %>% 
    calculate_bhar_from_price_df(target_duration = 12 * temp_horizon) %>% 
    mutate(horizon = temp_horizon)
  
  
  
  
})

```


```{r output_table_bhar_monthly_multiple}

bhar_monthly_multi %>% 
  group_by(horizon) %>% 
  summarise(across(c(contains("bhar"), duration), mean))

```


\subsection{Calendar-time portfolio abnormal returns}
