---
title: "TASE companies evolution"
output: pdf_document
---

```{r setup, include=FALSE,}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```


```{r Load_libraries}

library(devtools)

library(tidyverse)

library(xts)

library(stargazer)

library(readxl)

load_all()

```


```{r Import_data}

status_df = import.TASE.comps_status()

```


```{r plot_comps_evolution, fig.height=7}

ggplot(status_df %>% 
  filter(Sector == "Total"), aes(x = Year, y = End_Year, group = 1)) + 
  geom_col() + 
  geom_text(aes(x = Year, y = End_Year, label = End_Year), vjust = -1, color = "magenta") + 
  labs(x = "", y = "", title = "Number of listed companies in TASE") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))

```

Number of listed companies has been declining since it peaked at 2007-2008


```{r plot_comps_evolution_by_sectype}

ggplot(status_df %>% 
  filter(Sector %in% c("Total Shares","Total Bonds")),
  aes(x = Year, y = End_Year, group = Sector, fill = Sector)) + 
  geom_col() + 
  labs(x = "", y = "", title = "Number of listed companies in TASE") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

```


```{r plot_comps_evolution_by_sector}

ggplot(status_df %>% 
  filter(!Sector %in% grep("Total",unique(Sector),value = TRUE)),
  aes(x = Year, y = End_Year, group = Sector, fill = Sector)) + 
  geom_col() + 
  labs(x = "", y = "", title = "Number of listed companies in TASE") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

```

