
```{r load_libraries}

library(tidyverse)

library(zoo)

library(lubridate)

```


```{r Import_tase_comps_list}

del_comps_filepath = paste0("C:\\Users\\internet",
                            "\\OneDrive - Bank Of Israel",
                            "\\Data\\TASE liquidity",
                            "\\michael files\\delisted_comps.csv")

ipo_filepath = paste0("C:\\Users\\internet",
                            "\\OneDrive - Bank Of Israel",
                            "\\Data\\TASE liquidity",
                            "\\michael files\\ipo_dates.csv")

delisted_comps = read_csv(del_comps_filepath,
                          show_col_types = FALSE)

ipo_comps = read_csv(ipo_filepath,
                          show_col_types = FALSE) %>% 
  select(tase_id, ipo_date) %>% 
  mutate(ipo_date = as_date(ipo_date, format = "%d/%m/%Y"))



ipo_comps = ipo_comps %>% 
  left_join(delisted_comps %>% 
              select(tase_id) %>% 
              distinct() %>% 
              mutate(delisted = 1)) %>% 
  mutate(delisted = replace_na(delisted,0))


rm(del_comps_filepath, ipo_filepath)

```


```{r match_delisted_and_control_by_market}

market_df = read_rds(paste0("C:\\Users\\internet",
                            "\\OneDrive - Bank Of Israel\\Data",
                            "\\TASE liquidity\\Rdata files",
                            "\\market_data_2022-11-15.rds")) %>% 
  select(tase_id = tase_issuer_id,date = date_value, market_value) %>% 
  filter(complete.cases(.))

market_df = market_df %>% 
  group_by(tase_id, date = as.yearmon(date)) %>% 
  summarise(market_value = mean(as.numeric(market_value),
                                na.rm = TRUE), .groups = "drop")
  

delisted_comps= ipo_comps %>%
  filter(delisted == 1) %>% 
  select(-delisted) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(ipo_date = as.yearmon(ipo_date)) %>% 
  left_join(market_df, by = c("tase_id", "ipo_date" = "date")) %>% 
  filter(complete.cases(.))


control_comps = ipo_comps %>%
  filter(delisted == 0) %>% 
  select(-delisted) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(ipo_date = as.yearmon(ipo_date)) %>% 
  left_join(market_df, by = c("tase_id", "ipo_date" = "date")) %>% 
  filter(complete.cases(.))


matching_table_by_market = delisted_comps %>% 
  full_join(control_comps,
            by = "ipo_date",
            suffix = c("_delisted","_control")) %>% 
  mutate(diff = market_value_delisted / market_value_control - 1) %>% 
  filter(abs(diff) <= 0.15) %>%
  select(starts_with("tase_id"),ipo_date)

rm(control_comps, delisted_comps, market_df)

```



```{r match_delisted_and_control_by_size}

df = read_rds(paste0("C:\\Users\\internet",
                     "\\OneDrive - Bank Of Israel\\Data",
                     "\\TASE liquidity\\Rdata files",
                     "\\final_df_2022-11-20.rds"))

assets_df = df %>% 
  select(tase_id, date, size) %>% 
  filter(complete.cases(.))

delisted_comps= ipo_comps %>%
  filter(delisted == 1) %>% 
  select(-delisted) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(ipo_date = as.yearqtr(ipo_date)) %>% 
  left_join(assets_df, by = c("tase_id", "ipo_date" = "date")) %>% 
  filter(complete.cases(.))


control_comps = ipo_comps %>%
  filter(delisted == 0) %>% 
  select(-delisted) %>% 
  mutate(tase_id = as.character(tase_id)) %>% 
  mutate(ipo_date = as.yearqtr(ipo_date)) %>% 
  left_join(assets_df, by = c("tase_id", "ipo_date" = "date")) %>% 
  filter(complete.cases(.))


matching_table_by_size = delisted_comps %>% 
  full_join(control_comps,
            by = "ipo_date",
            suffix = c("_delisted","_control")) %>% 
  mutate(diff = size_delisted / size_control - 1) %>% 
  filter(abs(diff) <= 0.15) %>%
  select(starts_with("tase_id"),ipo_date)

rm(control_comps, delisted_comps, assets_df)

```

```{r save_matching_df}

matching_table_by_size %>% 
  write_csv(paste0("C:\\Users\\internet",
                   "\\OneDrive - Bank Of Israel",
                   "\\Data\\TASE liquidity",
                   "\\michael files\\matching_table_by_size.csv"))


```

```{r summary_control_vs_delisted}

delisted_comps_filepath = paste0("C:\\Users\\internet",
                                 "\\OneDrive - Bank Of Israel",
                                 "\\Data\\TASE liquidity",
                                 "\\michael files",
                                 "\\delisted_comps.csv")

delisted_comps = read_csv(delisted_comps_filepath,
                          col_types = "cc",
                          show_col_types = FALSE) %>% 
  mutate(delisting_date = as.yearqtr(delisting_date,
                                     format = "%m/%d/%y"))

matching_table_by_size = matching_table_by_size %>% 
  left_join(delisted_comps, by = c("tase_id_delisted" = "tase_id"))


control_df = df %>% 
  inner_join(matching_table_by_size %>% 
               select(tase_id_control),
             by = c("tase_id" = "tase_id_control")) %>% 
  rename(tase_id_control = tase_id)


```

